name: immich

services:

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    hostname: immich
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc
    volumes:
      - ${EXTERNAL_PATH}:/data
      - ${UPLOAD_LOCATION}:/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/c/:/mnt/c:ro
      - /mnt/d/:/mnt/d:ro
      - /mnt/g/:/mnt/g:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    healthcheck:
      disable: false
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started


  immich-db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich_postgres
    hostname: immich-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: on-failure:5


  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    container_name: immich_redis
    hostname: immich-redis
    volumes:
      - ${EXTERNAL_PATH}/redis:/data:rw
    healthcheck:
      test: redis-cli ping || exit 1
    restart: on-failure:5


  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    container_name: immich_machine_learning
    hostname: immich-machine-learning
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: true
    restart: unless-stopped


  immich-nginx:
    image: nginx:1.27-alpine
    container_name: immich_nginx
    restart: unless-stopped
    depends_on:
      - immich-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./immich.crt:/etc/nginx/certs/immich.crt:ro
      - ./immich.key:/etc/nginx/certs/immich.key:ro


  pgdata_export:
    image: ubuntu:24.04
    profiles: ["tools"]
    env_file:
      - .env
    environment:
      BACKUP_DIR: ${BACKUP_DIR:-/tmp/immich-backup}
    volumes:
      - ${DB_DATA_LOCATION}:/from:ro
      - ${BACKUP_DIR:-/tmp/immich-backup}:/backup
    command: ["bash", "-lc", "mkdir -p /backup/pgdata && cp -a /from/. /backup/pgdata/ && sync && echo 'Export done'"]


  pg_dump:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    profiles: ["tools"]
    env_file:
      - .env
    environment:
      PGPASSWORD: ${DB_PASSWORD}
      BACKUP_DIR: ${BACKUP_DIR:-/tmp/immich-backup}
    volumes:
      - ${BACKUP_DIR:-/tmp/immich-backup}:/backup
    entrypoint: ["/bin/bash","-lc"]
    command:
      - >
        pg_dumpall -h immich-db -p 5432 -U "${DB_USERNAME}" -c > "/backup/immich-db_$(date +%Y%m%d%H%M%S).sql"


  pg_restore:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    profiles: ["tools"]
    env_file:
      - .env
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ${RESTORE_FILE:-/tmp/immich-restore.sql}:/restore.sql:ro
    entrypoint: ["/bin/bash","-lc"]
    command:
      - >
        psql -h immich-db -p 5432 -U "${DB_USERNAME}" -f /restore.sql


volumes:
  model-cache:
